"""Built-in default DAT catalogue (shown before first Update)."""
from __future__ import annotations

# (rel, enabled) — seeded into dats/dat_sources.json on first run
DEFAULT_DAT_SOURCES = [
    ('MiSTer_Arcade (20260707).dat', True),
    ('MiSTer_Arcade_HBMAME (20260707).dat', True),
    ('MiSTer_Arcade_MAME (20260707).dat', True),
    ('MiSTer_Computer (20260707).dat', True),
    ('MiSTer_Console (20260807).dat', True),
    ('MiSTer_Console_CD (20260707).dat', True),
    ('MiSTer_Console_CD_CHD (20260707).dat', True),
    ('MiSTer_Extras (20260707).dat', True),
    ('Atari - 2600.dat', True),
    ('Atari - 5200.dat', True),
    ('Atari - 7800.dat', True),
    ('Atari - 8-bit Family.dat', True),
    ('Atari - Jaguar.dat', True),
    ('Atari - Lynx.dat', True),
    ('Bandai - WonderSwan Color.dat', True),
    ('Bandai - WonderSwan.dat', True),
    ('Casio - PV-1000.dat', True),
    ('Coleco - ColecoVision.dat', True),
    ('Commodore - 64.dat', True),
    ('Commodore - Amiga.dat', True),
    ('Commodore - VIC-20.dat', True),
    ('Emerson - Arcadia 2001.dat', True),
    ('Entex - Adventure Vision.dat', True),
    ('Epoch - Super Cassette Vision.dat', True),
    ('Fairchild - Channel F.dat', True),
    ('GCE - Vectrex.dat', True),
    ('Interton - VC 4000.dat', True),
    ('Magnavox - Odyssey2.dat', True),
    ('Mattel - Intellivision.dat', True),
    ('Microsoft - MSX.dat', True),
    ('NEC - PC Engine - TurboGrafx 16.dat', True),
    ('NEC - PC Engine CD - TurboGrafx-CD.dat', True),
    ('NEC - PC Engine SuperGrafx.dat', True),
    ('Nintendo - Family Computer Disk System.dat', True),
    ('Nintendo - Game Boy Advance.dat', True),
    ('Nintendo - Game Boy Color.dat', True),
    ('Nintendo - Game Boy.dat', True),
    ('Nintendo - Nintendo 64.dat', True),
    ('Nintendo - Nintendo Entertainment System.dat', True),
    ('Nintendo - Pokemon Mini.dat', True),
    ('Nintendo - Satellaview.dat', True),
    ('Nintendo - Sufami Turbo.dat', True),
    ('Nintendo - Super Nintendo Entertainment System.dat', True),
    ('Philips - CD-i.dat', True),
    ('Philips - Videopac+.dat', True),
    ('RCA - Studio II.dat', True),
    ('Sega - 32X.dat', True),
    ('Sega - Dreamcast.dat', True),
    ('Sega - Game Gear.dat', True),
    ('Sega - Master System - Mark III.dat', True),
    ('Sega - Mega Drive - Genesis.dat', True),
    ('Sega - Mega-CD - Sega CD.dat', True),
    ('Sega - Saturn.dat', True),
    ('Sega - SG-1000.dat', True),
    ('Sharp - X68000.dat', True),
    ('SNK - Neo Geo CD.dat', True),
    ('SNK - Neo Geo Pocket Color.dat', True),
    ('SNK - Neo Geo Pocket.dat', True),
    ('Sony - PlayStation.dat', True),
    ('The 3DO Company - 3DO.dat', True),
    ('VTech - CreatiVision.dat', True),
    ('Watara - Supervision.dat', True),
]

